// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Message: typeof import('./components/Message.vue')['default']
    MessageOld: typeof import('./components/MessageOld.vue')['default']
    Redbutton: typeof import('./components/Redbutton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TodoItem: typeof import('./components/TodoItem.vue')['default']
    TodoList: typeof import('./components/TodoList.vue')['default']
  }
}

export { }
