// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    MessageOld: typeof import('./components/MessageOld.vue')['default']
    Redbutton: typeof import('./components/Redbutton.vue')['default']
  }
}

export { }
